# Name of the GitHub Actions workflow shown in GitHub UI
name: Java CI with Maven - POC

# Define triggers: run on push or PR to 'main' branch
on:
  push:
    branches: [ "main" ]  # Trigger on push to main branch
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to main

jobs:
  build-and-push-poc:  # Unique job ID
    runs-on: ubuntu-latest  # GitHub-hosted runner environment

    steps:
      # Step 1: Checkout your repo code
      - name: Checkout code - POC
        uses: actions/checkout@v4  # Uses GitHub’s official action to clone your repo

      # Step 2: Set up Java 17 for Maven build
      - name: Set up JDK 17 - POC
        uses: actions/setup-java@v4  # Official Java setup action
        with:
          java-version: '17'  # Specify Java version
          distribution: 'temurin'  # Use Eclipse Temurin (open-source JDK)
          cache: maven  # Enable caching of dependencies to speed up builds

      # Step 3: Build Java project using Maven
      - name: Build with Maven - POC
        run:  mvn clean --file pom.xml  # -B = batch mode (no prompts), builds with pom.xml

      # Step 4: Authenticate GitHub Actions with your GCP account
      - name: Authenticate with GCP - POC
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'  # Uses GCP service account key stored as secret

      # Step 5: Configure Docker to push to GCP Artifact Registry
      - name: Configure Docker for Artifact Registry - POC
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet  # Auth Docker with Artifact Registry

      # Step 6: Build Docker image using Dockerfile in your repo
      - name: Build Docker Image - POC
        run: |
          docker build -t europe-west1-docker.pkg.dev/poc-setup-462605/poc-docker-repo/poc-1:latest .
  
          # Builds image and tags it with Artifact Registry path

      # Step 7: Push the Docker image to GCP Artifact Registry
      - name: Push Docker Image - POC
        run: |
          docker push europe-west1-docker.pkg.dev/poc-setup-462605/poc-docker-repo/poc-1:latest
          # Pushes built image to the Artifact Registry
